package greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.igrs.beacon.model.data.UUIDBean;

import greendao.UUIDBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig uUIDBeanDaoConfig;

    private final UUIDBeanDao uUIDBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        uUIDBeanDaoConfig = daoConfigMap.get(UUIDBeanDao.class).clone();
        uUIDBeanDaoConfig.initIdentityScope(type);

        uUIDBeanDao = new UUIDBeanDao(uUIDBeanDaoConfig, this);

        registerDao(UUIDBean.class, uUIDBeanDao);
    }
    
    public void clear() {
        uUIDBeanDaoConfig.clearIdentityScope();
    }

    public UUIDBeanDao getUUIDBeanDao() {
        return uUIDBeanDao;
    }

}
